#pragma once
#ifdef FILEACCESS_USER
#include <winioctl.h>
#else
#endif

#define CTL_MFS_INIT_USER_EVENTS CTL_CODE(FILE_DEVICE_UNKNOWN,0x89F,METHOD_BUFFERED,FILE_ANY_ACCESS)



#define CTL_MFS_ADD_PROTECT CTL_CODE(FILE_DEVICE_UNKNOWN,0x8B1,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define CTL_MFS_REMOVE_PROTECT CTL_CODE(FILE_DEVICE_UNKNOWN,0x8B1,METHOD_BUFFERED,FILE_ANY_ACCESS)