//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMgr.Lanuages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanuageResource_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanuageResource_zh() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCMgr.Lanuages.LanuageResource_zh", typeof(LanuageResource_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝访问 的本地化字符串。
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动时间 的本地化字符串。
        /// </summary>
        internal static string ActiveTime {
            get {
                return ResourceManager.GetString("ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务管理器 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疑问 的本地化字符串。
        /// </summary>
        internal static string AskTitle {
            get {
                return ResourceManager.GetString("AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属线程 的本地化字符串。
        /// </summary>
        internal static string BelongThread {
            get {
                return ResourceManager.GetString("BelongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束进程(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string BtnEndProcess {
            get {
                return ResourceManager.GetString("BtnEndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束任务(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string BtnEndTask {
            get {
                return ResourceManager.GetString("BtnEndTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string BtnRestartText {
            get {
                return ResourceManager.GetString("BtnRestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存： 的本地化字符串。
        /// </summary>
        internal static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已缓存 的本地化字符串。
        /// </summary>
        internal static string Cached {
            get {
                return ResourceManager.GetString("Cached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消运行 的本地化字符串。
        /// </summary>
        internal static string CancelRun {
            get {
                return ResourceManager.GetString("CancelRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法复制文件 的本地化字符串。
        /// </summary>
        internal static string CantCopyFile {
            get {
                return ResourceManager.GetString("CantCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取路径。 的本地化字符串。
        /// </summary>
        internal static string CantGetPath {
            get {
                return ResourceManager.GetString("CantGetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法移动文件 的本地化字符串。
        /// </summary>
        internal static string CantMoveFile {
            get {
                return ResourceManager.GetString("CantMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法改变服务设置 的本地化字符串。
        /// </summary>
        internal static string ChangeScStartTypeFailed {
            get {
                return ResourceManager.GetString("ChangeScStartTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您更改了窗口文字，要把文字设置到窗口上吗？ 的本地化字符串。
        /// </summary>
        internal static string ChangeWindowTextAsk {
            get {
                return ResourceManager.GetString("ChangeWindowTextAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您更改了窗口文字，要把文字设置到窗口上吗？ 的本地化字符串。
        /// </summary>
        internal static string ChangeWindowTextAsk1 {
            get {
                return ResourceManager.GetString("ChangeWindowTextAsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标文件夹 的本地化字符串。
        /// </summary>
        internal static string ChooseTargetDir {
            get {
                return ResourceManager.GetString("ChooseTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在计算删除项目... 的本地化字符串。
        /// </summary>
        internal static string CollectingFiles {
            get {
                return ResourceManager.GetString("CollectingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换次数 的本地化字符串。
        /// </summary>
        internal static string ContextSwitch {
            get {
                return ResourceManager.GetString("ContextSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续运行 的本地化字符串。
        /// </summary>
        internal static string ContinueRun {
            get {
                return ResourceManager.GetString("ContinueRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在复制文件…… 的本地化字符串。
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑处理器： 的本地化字符串。
        /// </summary>
        internal static string CpuCpunt {
            get {
                return ResourceManager.GetString("CpuCpunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内核： 的本地化字符串。
        /// </summary>
        internal static string CpuPackageCount {
            get {
                return ResourceManager.GetString("CpuPackageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反汇编大小过大，双击此条目继续反汇编 的本地化字符串。
        /// </summary>
        internal static string DblClickToDa {
            get {
                return ResourceManager.GetString("DblClickToDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真的要删除这个文件？ 的本地化字符串。
        /// </summary>
        internal static string DelAsk1 {
            get {
                return ResourceManager.GetString("DelAsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真的要删除这 %d 个文件？ 的本地化字符串。
        /// </summary>
        internal static string DelAsk2 {
            get {
                return ResourceManager.GetString("DelAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真的要删除这个文件夹？ 的本地化字符串。
        /// </summary>
        internal static string DelAsk3 {
            get {
                return ResourceManager.GetString("DelAsk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在删除... 的本地化字符串。
        /// </summary>
        internal static string DeleteFiles {
            get {
                return ResourceManager.GetString("DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除中…… 的本地化字符串。
        /// </summary>
        internal static string DeleteIng {
            get {
                return ResourceManager.GetString("DeleteIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DelFailed {
            get {
                return ResourceManager.GetString("DelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除服务 的本地化字符串。
        /// </summary>
        internal static string DelScError {
            get {
                return ResourceManager.GetString("DelScError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除此启动项以不可恢复，您需要确定此启动项不是系统必须，否则删除可能会对您的系统造成无法正常运行的问题。 的本地化字符串。
        /// </summary>
        internal static string DelStartupItemAsk {
            get {
                return ResourceManager.GetString("DelStartupItemAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除此启动项以及文件不可恢复，您需要确定此文件不是系统必须文件，否则删除可能会对您的系统造成破坏。 的本地化字符串。
        /// </summary>
        internal static string DelStartupItemAsk2 {
            get {
                return ResourceManager.GetString("DelStartupItemAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除确认 的本地化字符串。
        /// </summary>
        internal static string DelSure {
            get {
                return ResourceManager.GetString("DelSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动 的本地化字符串。
        /// </summary>
        internal static string DemandStart {
            get {
                return ResourceManager.GetString("DemandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不要再提醒我了 的本地化字符串。
        /// </summary>
        internal static string DoNotRemidMeLater {
            get {
                return ResourceManager.GetString("DoNotRemidMeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动数： 的本地化字符串。
        /// </summary>
        internal static string DriverCount {
            get {
                return ResourceManager.GetString("DriverCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其中已加载： 的本地化字符串。
        /// </summary>
        internal static string DriverCountLoaded {
            get {
                return ResourceManager.GetString("DriverCountLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动加载 的本地化字符串。
        /// </summary>
        internal static string DriverLoad {
            get {
                return ResourceManager.GetString("DriverLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动加载失败。Lset Error : {0} . 更多信息请查看调试输出窗口。 的本地化字符串。
        /// </summary>
        internal static string DriverLoadFailed {
            get {
                return ResourceManager.GetString("DriverLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动加载成功。 的本地化字符串。
        /// </summary>
        internal static string DriverLoadSuccessFull {
            get {
                return ResourceManager.GetString("DriverLoadSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动卸载失败。Lset Error : {0} . 更多信息请查看调试输出窗口。 的本地化字符串。
        /// </summary>
        internal static string DriverUnLoadFailed {
            get {
                return ResourceManager.GetString("DriverUnLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动卸载成功。 的本地化字符串。
        /// </summary>
        internal static string DriverUnLoadSuccessFull {
            get {
                return ResourceManager.GetString("DriverUnLoadSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法结束进程 的本地化字符串。
        /// </summary>
        internal static string EndProcFailed {
            get {
                return ResourceManager.GetString("EndProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口点 的本地化字符串。
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法枚举模块 的本地化字符串。
        /// </summary>
        internal static string EnumModuleFailed {
            get {
                return ResourceManager.GetString("EnumModuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举线程失败 的本地化字符串。
        /// </summary>
        internal static string EnumThreadFailed {
            get {
                return ResourceManager.GetString("EnumThreadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ErrTitle {
            get {
                return ResourceManager.GetString("ErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提权失败！ 的本地化字符串。
        /// </summary>
        internal static string FailedGetPrivileges {
            get {
                return ResourceManager.GetString("FailedGetPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FileCopyed {
            get {
                return ResourceManager.GetString("FileCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经剪切到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FileCuted {
            get {
                return ResourceManager.GetString("FileCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经存在 的本地化字符串。
        /// </summary>
        internal static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经存在，覆盖吗？ 的本地化字符串。
        /// </summary>
        internal static string FileExist2 {
            get {
                return ResourceManager.GetString("FileExist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件没有签名 的本地化字符串。
        /// </summary>
        internal static string FileNotTrust {
            get {
                return ResourceManager.GetString("FileNotTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件系统 的本地化字符串。
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经签名 的本地化字符串。
        /// </summary>
        internal static string FileTrust {
            get {
                return ResourceManager.GetString("FileTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;A HREF=&quot;#&quot;&gt;查看证书&lt;/A&gt; 的本地化字符串。
        /// </summary>
        internal static string FileTrustViewCrt {
            get {
                return ResourceManager.GetString("FileTrustViewCrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充文件失败 的本地化字符串。
        /// </summary>
        internal static string FillFileFailed {
            get {
                return ResourceManager.GetString("FillFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充文件的大小不能为 0 ！ 的本地化字符串。
        /// </summary>
        internal static string FillFileNeedSize {
            get {
                return ResourceManager.GetString("FillFileNeedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充文件成功 的本地化字符串。
        /// </summary>
        internal static string FillFileSuccess {
            get {
                return ResourceManager.GetString("FillFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FolderCopyed {
            get {
                return ResourceManager.GetString("FolderCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已经剪切到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FolderCuted {
            get {
                return ResourceManager.GetString("FolderCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的文件夹已经存在 的本地化字符串。
        /// </summary>
        internal static string FolderHasExist {
            get {
                return ResourceManager.GetString("FolderHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载模块错误 的本地化字符串。
        /// </summary>
        internal static string FreeFailed {
            get {
                return ResourceManager.GetString("FreeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法Free模块，进程已退出。 的本地化字符串。
        /// </summary>
        internal static string FreeInvalidProc {
            get {
                return ResourceManager.GetString("FreeInvalidProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载模块成功。 的本地化字符串。
        /// </summary>
        internal static string FreeLibSuccess {
            get {
                return ResourceManager.GetString("FreeLibSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制删除成功 的本地化字符串。
        /// </summary>
        internal static string FroceDelSuccess {
            get {
                return ResourceManager.GetString("FroceDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能正在开发中，敬请期待！ 的本地化字符串。
        /// </summary>
        internal static string FunCreateing {
            get {
                return ResourceManager.GetString("FunCreateing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取失败 的本地化字符串。
        /// </summary>
        internal static string GetFailed {
            get {
                return ResourceManager.GetString("GetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取文件信息失败 的本地化字符串。
        /// </summary>
        internal static string GetFileInfoFailed {
            get {
                return ResourceManager.GetString("GetFileInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 句柄数 的本地化字符串。
        /// </summary>
        internal static string HandleCount {
            get {
                return ResourceManager.GetString("HandleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名无效。 的本地化字符串。
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效窗口。 的本地化字符串。
        /// </summary>
        internal static string InvalidHwnd {
            get {
                return ResourceManager.GetString("InvalidHwnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效进程 的本地化字符串。
        /// </summary>
        internal static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效线程。 的本地化字符串。
        /// </summary>
        internal static string InvThread {
            get {
                return ResourceManager.GetString("InvThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内核服务 的本地化字符串。
        /// </summary>
        internal static string KernelDriver {
            get {
                return ResourceManager.GetString("KernelDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内核没有启动。 的本地化字符串。
        /// </summary>
        internal static string KernelNotLoad {
            get {
                return ResourceManager.GetString("KernelNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果某个打开的程序与此进程关联，则会关闭此程序并且将丢失所有未保存的数据。如果结束某个系统进程，则可能导致系统不稳定。你确定要继续吗 ? 的本地化字符串。
        /// </summary>
        internal static string KillAskContent {
            get {
                return ResourceManager.GetString("KillAskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束此进程将导致 Windows 不稳定或关闭，从而导致丢失所有未保存的数据。你确定要继续吗? 的本地化字符串。
        /// </summary>
        internal static string KillAskContentImporant {
            get {
                return ResourceManager.GetString("KillAskContentImporant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请注意，强制结束此进程将导致系统立即奔溃！ 的本地化字符串。
        /// </summary>
        internal static string KillAskContentVeryImporant {
            get {
                return ResourceManager.GetString("KillAskContentVeryImporant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吗？ 的本地化字符串。
        /// </summary>
        internal static string KillAskEnd {
            get {
                return ResourceManager.GetString("KillAskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放弃未保存的数据并关闭。 的本地化字符串。
        /// </summary>
        internal static string KillAskImporantGiveup {
            get {
                return ResourceManager.GetString("KillAskImporantGiveup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你希望结束 的本地化字符串。
        /// </summary>
        internal static string KillAskStart {
            get {
                return ResourceManager.GetString("KillAskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法结束进程 的本地化字符串。
        /// </summary>
        internal static string KillFailed {
            get {
                return ResourceManager.GetString("KillFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个 PCMgr 无法结束，您可以手动结束它 的本地化字符串。
        /// </summary>
        internal static string KillOldFailed {
            get {
                return ResourceManager.GetString("KillOldFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个 PCMgr 已经成功结束 的本地化字符串。
        /// </summary>
        internal static string KillOldSuccess {
            get {
                return ResourceManager.GetString("KillOldSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法结束线程 的本地化字符串。
        /// </summary>
        internal static string KillThreadError {
            get {
                return ResourceManager.GetString("KillThreadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法结束线程，无效线程。 的本地化字符串。
        /// </summary>
        internal static string KillThreadInvThread {
            get {
                return ResourceManager.GetString("KillThreadInvThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置只有您重新打开软件才会生效 的本地化字符串。
        /// </summary>
        internal static string LanuageChangedTip {
            get {
                return ResourceManager.GetString("LanuageChangedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载内核驱动 的本地化字符串。
        /// </summary>
        internal static string LoadDriver {
            get {
                return ResourceManager.GetString("LoadDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载驱动失败！ 的本地化字符串。
        /// </summary>
        internal static string LoadDriverErr {
            get {
                return ResourceManager.GetString("LoadDriverErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要 64 位的程序来加载内核驱动 的本地化字符串。
        /// </summary>
        internal static string LoadDriverErrNeed64 {
            get {
                return ResourceManager.GetString("LoadDriverErrNeed64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 64 位系统中 PC Manager 需要 以 64 位模式运行才能正确加载驱动并调用内核。
        ///因此，内核功能不可用，如果您需要使用内核功能，请切换至 64 位PC Manager 程序 的本地化字符串。
        /// </summary>
        internal static string LoadDriverErrNeed64Text {
            get {
                return ResourceManager.GetString("LoadDriverErrNeed64Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务 的本地化字符串。
        /// </summary>
        internal static string LocalService {
            get {
                return ResourceManager.GetString("LocalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务（模拟） 的本地化字符串。
        /// </summary>
        internal static string LocalServiceAndNoImpersonation {
            get {
                return ResourceManager.GetString("LocalServiceAndNoImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务（网络受限） 的本地化字符串。
        /// </summary>
        internal static string LocalServiceNetworkRestricted {
            get {
                return ResourceManager.GetString("LocalServiceNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务（无网络） 的本地化字符串。
        /// </summary>
        internal static string LocalServiceNoNetwork {
            get {
                return ResourceManager.GetString("LocalServiceNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地系统 的本地化字符串。
        /// </summary>
        internal static string LocalSystem {
            get {
                return ResourceManager.GetString("LocalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地系统（网络受限） 的本地化字符串。
        /// </summary>
        internal static string LocalSystemNetworkRestricted {
            get {
                return ResourceManager.GetString("LocalSystemNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大速度： 的本地化字符串。
        /// </summary>
        internal static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用中 (已缓存) 的本地化字符串。
        /// </summary>
        internal static string MemUsing {
            get {
                return ResourceManager.GetString("MemUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用内存 的本地化字符串。
        /// </summary>
        internal static string MenCanUse {
            get {
                return ResourceManager.GetString("MenCanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以管理员模式重启程序 的本地化字符串。
        /// </summary>
        internal static string MenuRebootAsAdmin {
            get {
                return ResourceManager.GetString("MenuRebootAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名 的本地化字符串。
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块路径 的本地化字符串。
        /// </summary>
        internal static string ModulePath {
            get {
                return ResourceManager.GetString("ModulePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在移动文件…… 的本地化字符串。
        /// </summary>
        internal static string Moveing {
            get {
                return ResourceManager.GetString("Moveing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件需要更多的权限... 的本地化字符串。
        /// </summary>
        internal static string NeedAdmin {
            get {
                return ResourceManager.GetString("NeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络服务 的本地化字符串。
        /// </summary>
        internal static string NetworkService {
            get {
                return ResourceManager.GetString("NetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络服务（模拟） 的本地化字符串。
        /// </summary>
        internal static string NetworkServiceAndNoImpersonation {
            get {
                return ResourceManager.GetString("NetworkServiceAndNoImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络服务（网络受限） 的本地化字符串。
        /// </summary>
        internal static string NetworkServiceNetworkRestricted {
            get {
                return ResourceManager.GetString("NetworkServiceNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹失败 的本地化字符串。
        /// </summary>
        internal static string NewFolderFailed {
            get {
                return ResourceManager.GetString("NewFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹成功 的本地化字符串。
        /// </summary>
        internal static string NewFolderSuccess {
            get {
                return ResourceManager.GetString("NewFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在刚才的对话框中选择”是“或者”确定“来赋予本程序管理员权限。 的本地化字符串。
        /// </summary>
        internal static string NoAdminTipText {
            get {
                return ResourceManager.GetString("NoAdminTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您拒绝了权限赋予。 的本地化字符串。
        /// </summary>
        internal static string NoAdminTipTitle {
            get {
                return ResourceManager.GetString("NoAdminTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非分页缓冲池 的本地化字符串。
        /// </summary>
        internal static string NonPagedPool {
            get {
                return ResourceManager.GetString("NonPagedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法下载或加载NTOS的符号文件 的本地化字符串。
        /// </summary>
        internal static string NoPDBWarn {
            get {
                return ResourceManager.GetString("NoPDBWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们需要NTOS的pdb文件才能对内核进行分析，发挥出软件的所有功能。因此，内核的部分功能将被禁用。
        ///您也可以尝试用WinDbg来下载NTOS的符号文件，然后将其复制到本软件目录\symbols文件夹下，我们将会自动加载。 的本地化字符串。
        /// </summary>
        internal static string NoPDBWarnText {
            get {
                return ResourceManager.GetString("NoPDBWarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您想打开此文件吗？ 的本地化字符串。
        /// </summary>
        internal static string OpenAsk {
            get {
                return ResourceManager.GetString("OpenAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开进程 的本地化字符串。
        /// </summary>
        internal static string OpenProcFailed {
            get {
                return ResourceManager.GetString("OpenProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开服务失败 的本地化字符串。
        /// </summary>
        internal static string OpenServiceError {
            get {
                return ResourceManager.GetString("OpenServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开线程 的本地化字符串。
        /// </summary>
        internal static string OpenThreadFailed {
            get {
                return ResourceManager.GetString("OpenThreadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法完成此操作 的本地化字符串。
        /// </summary>
        internal static string OpFailed {
            get {
                return ResourceManager.GetString("OpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string OpSuccess {
            get {
                return ResourceManager.GetString("OpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页缓冲池 的本地化字符串。
        /// </summary>
        internal static string PagedPool {
            get {
                return ResourceManager.GetString("PagedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string PathCopyed {
            get {
                return ResourceManager.GetString("PathCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 :  的本地化字符串。
        /// </summary>
        internal static string PathStart {
            get {
                return ResourceManager.GetString("PathStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string PathUnExists {
            get {
                return ResourceManager.GetString("PathUnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入一个驱动路径或选择一个驱动！ 的本地化字符串。
        /// </summary>
        internal static string PleaseChooseDriver {
            get {
                return ResourceManager.GetString("PleaseChooseDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入反汇编大小 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterDaSize {
            get {
                return ResourceManager.GetString("PleaseEnterDaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入驱动刚才加载的服务名 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterDriverServiceName {
            get {
                return ResourceManager.GetString("PleaseEnterDriverServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要跳转的路径！ 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterPath {
            get {
                return ResourceManager.GetString("PleaseEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入目标地址 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterTargetAddress {
            get {
                return ResourceManager.GetString("PleaseEnterTargetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32位 的本地化字符串。
        /// </summary>
        internal static string Process32Bit {
            get {
                return ResourceManager.GetString("Process32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程数 的本地化字符串。
        /// </summary>
        internal static string ProcessCount {
            get {
                return ResourceManager.GetString("ProcessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队列时间 的本地化字符串。
        /// </summary>
        internal static string QueueTime {
            get {
                return ResourceManager.GetString("QueueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取速度 的本地化字符串。
        /// </summary>
        internal static string ReadSpeed {
            get {
                return ResourceManager.GetString("ReadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪  共 的本地化字符串。
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个项目 的本地化字符串。
        /// </summary>
        internal static string ReadyStatusEnd {
            get {
                return ResourceManager.GetString("ReadyStatusEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个项目  选择了 的本地化字符串。
        /// </summary>
        internal static string ReadyStatusEnd2 {
            get {
                return ResourceManager.GetString("ReadyStatusEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收 的本地化字符串。
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新成功。 的本地化字符串。
        /// </summary>
        internal static string RefeshSuccess {
            get {
                return ResourceManager.GetString("RefeshSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到您没有赋予 PCMgr 管理员权限，这会导致一些高级功能不可用。
        ///PCMgr 需要管理员权限 才能对系统进行控制和管理。
        ///了解什么是&lt;A HREF=&quot;#&quot;&gt;管理员权限&lt;/A&gt;。
        ///了解本软件使用&lt;A HREF=&quot;#&quot;&gt;管理员权限控制和管理的详情&lt;/A&gt;。 的本地化字符串。
        /// </summary>
        internal static string RequestAdminText {
            get {
                return ResourceManager.GetString("RequestAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我需要更多权限 的本地化字符串。
        /// </summary>
        internal static string RequestAdminTitle {
            get {
                return ResourceManager.GetString("RequestAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法继续进程运行 的本地化字符串。
        /// </summary>
        internal static string ResProcFailed {
            get {
                return ResourceManager.GetString("ResProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法继续线程运行 的本地化字符串。
        /// </summary>
        internal static string ReThreadErr {
            get {
                return ResourceManager.GetString("ReThreadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制结束上一个 PCMgr 的本地化字符串。
        /// </summary>
        internal static string Run2KillOld {
            get {
                return ResourceManager.GetString("Run2KillOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到您已经运行一个 PCMgr , 运行多个 PCMgr 可能导致软件功能异常，是否继续运行？
        ///如果上一个程序卡死或者无响应，您也可以选择强制结束上一个进程。 的本地化字符串。
        /// </summary>
        internal static string Run2WarnText {
            get {
                return ResourceManager.GetString("Run2WarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行64位版本 的本地化字符串。
        /// </summary>
        internal static string Run64 {
            get {
                return ResourceManager.GetString("Run64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以管理员身份重启软件 的本地化字符串。
        /// </summary>
        internal static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常运行时间 的本地化字符串。
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务数 的本地化字符串。
        /// </summary>
        internal static string ServiceCount {
            get {
                return ResourceManager.GetString("ServiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务主机 的本地化字符串。
        /// </summary>
        internal static string ServiceHost {
            get {
                return ResourceManager.GetString("ServiceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动服务管理器 的本地化字符串。
        /// </summary>
        internal static string StartSCMFailed {
            get {
                return ResourceManager.GetString("StartSCMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无响应 的本地化字符串。
        /// </summary>
        internal static string StatusHang {
            get {
                return ResourceManager.GetString("StatusHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行 的本地化字符串。
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已提交 的本地化字符串。
        /// </summary>
        internal static string Submited {
            get {
                return ResourceManager.GetString("Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的运行吗？ 的本地化字符串。
        /// </summary>
        internal static string SuspendEnd {
            get {
                return ResourceManager.GetString("SuspendEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要暂停 的本地化字符串。
        /// </summary>
        internal static string SuspendStart {
            get {
                return ResourceManager.GetString("SuspendStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制暂停此进程运行将导致 Windows 立即奔溃！ 的本地化字符串。
        /// </summary>
        internal static string SuspendVeryImporantWarnContent {
            get {
                return ResourceManager.GetString("SuspendVeryImporantWarnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制暂停此进程运行将导致 Windows 不稳定或关闭，从而导致丢失所有未保存的数据。你确定要继续吗? 的本地化字符串。
        /// </summary>
        internal static string SuspendWarnContent {
            get {
                return ResourceManager.GetString("SuspendWarnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法暂停进程运行 的本地化字符串。
        /// </summary>
        internal static string SusProcFailed {
            get {
                return ResourceManager.GetString("SusProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法挂起线程 的本地化字符串。
        /// </summary>
        internal static string SuThreadErr {
            get {
                return ResourceManager.GetString("SuThreadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不建议强制挂起线程，因为挂起线程极易发生死锁等其他问题，如果您不是在调试程序，请不要使用该方法。
        ///那么，确定强制挂起线程？ 的本地化字符串。
        /// </summary>
        internal static string SuThreadWarn {
            get {
                return ResourceManager.GetString("SuThreadWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统空闲进程 的本地化字符串。
        /// </summary>
        internal static string SystemIdleProcess {
            get {
                return ResourceManager.GetString("SystemIdleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统服务 的本地化字符串。
        /// </summary>
        internal static string SystemService {
            get {
                return ResourceManager.GetString("SystemService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程数 的本地化字符串。
        /// </summary>
        internal static string ThreadCount {
            get {
                return ResourceManager.GetString("ThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string TipTitle {
            get {
                return ResourceManager.GetString("TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台进程 的本地化字符串。
        /// </summary>
        internal static string TitleBackGround {
            get {
                return ResourceManager.GetString("TitleBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基地址 的本地化字符串。
        /// </summary>
        internal static string TitleBaseAddress {
            get {
                return ResourceManager.GetString("TitleBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令行 的本地化字符串。
        /// </summary>
        internal static string TitleCmdLine {
            get {
                return ResourceManager.GetString("TitleCmdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定继续吗？ 的本地化字符串。
        /// </summary>
        internal static string TitleContinue {
            get {
                return ResourceManager.GetString("TitleContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU 的本地化字符串。
        /// </summary>
        internal static string TitleCPU {
            get {
                return ResourceManager.GetString("TitleCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘 的本地化字符串。
        /// </summary>
        internal static string TitleDisk {
            get {
                return ResourceManager.GetString("TitleDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载顺序 的本地化字符串。
        /// </summary>
        internal static string TitleDriverLoadPath {
            get {
                return ResourceManager.GetString("TitleDriverLoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动名称 的本地化字符串。
        /// </summary>
        internal static string TitleDriverName {
            get {
                return ResourceManager.GetString("TitleDriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动对象 的本地化字符串。
        /// </summary>
        internal static string TitleDriverObj {
            get {
                return ResourceManager.GetString("TitleDriverObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动路径 的本地化字符串。
        /// </summary>
        internal static string TitleDriverPath {
            get {
                return ResourceManager.GetString("TitleDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务名 的本地化字符串。
        /// </summary>
        internal static string TitleDriverScName {
            get {
                return ResourceManager.GetString("TitleDriverScName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string TitleDriverSize {
            get {
                return ResourceManager.GetString("TitleDriverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPROCESS 的本地化字符串。
        /// </summary>
        internal static string TitleEProcess {
            get {
                return ResourceManager.GetString("TitleEProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        internal static string TitleFilePath {
            get {
                return ResourceManager.GetString("TitleFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定强制重启？您未保存的工作将会丢失！ 的本地化字符串。
        /// </summary>
        internal static string TitleFRebbot {
            get {
                return ResourceManager.GetString("TitleFRebbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定强制关机？您未保存的工作将会丢失！ 的本地化字符串。
        /// </summary>
        internal static string TitleFShutdown {
            get {
                return ResourceManager.GetString("TitleFShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整名称 的本地化字符串。
        /// </summary>
        internal static string TitleFullName {
            get {
                return ResourceManager.GetString("TitleFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装路径 的本地化字符串。
        /// </summary>
        internal static string TitleInstallDir {
            get {
                return ResourceManager.GetString("TitleInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将注销。 的本地化字符串。
        /// </summary>
        internal static string TitleLogoOff {
            get {
                return ResourceManager.GetString("TitleLogoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        internal static string TitleNet {
            get {
                return ResourceManager.GetString("TitleNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PID 的本地化字符串。
        /// </summary>
        internal static string TitlePID {
            get {
                return ResourceManager.GetString("TitlePID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程名称 的本地化字符串。
        /// </summary>
        internal static string TitleProcName {
            get {
                return ResourceManager.GetString("TitleProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程路径 的本地化字符串。
        /// </summary>
        internal static string TitleProcPath {
            get {
                return ResourceManager.GetString("TitleProcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布者 的本地化字符串。
        /// </summary>
        internal static string TitlePublisher {
            get {
                return ResourceManager.GetString("TitlePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疑问 的本地化字符串。
        /// </summary>
        internal static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存 的本地化字符串。
        /// </summary>
        internal static string TitleRam {
            get {
                return ResourceManager.GetString("TitleRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将重启。 的本地化字符串。
        /// </summary>
        internal static string TitleReboot {
            get {
                return ResourceManager.GetString("TitleReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册表路径 的本地化字符串。
        /// </summary>
        internal static string TitleRegPath {
            get {
                return ResourceManager.GetString("TitleRegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将重启。 的本地化字符串。
        /// </summary>
        internal static string TitleRestart {
            get {
                return ResourceManager.GetString("TitleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将关机 的本地化字符串。
        /// </summary>
        internal static string TitleShutdown {
            get {
                return ResourceManager.GetString("TitleShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string TitleStatus {
            get {
                return ResourceManager.GetString("TitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重要警告 的本地化字符串。
        /// </summary>
        internal static string TitleVeryWarn {
            get {
                return ResourceManager.GetString("TitleVeryWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows进程 的本地化字符串。
        /// </summary>
        internal static string TitleWinApp {
            get {
                return ResourceManager.GetString("TitleWinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unistack 服务组 的本地化字符串。
        /// </summary>
        internal static string UnistackSvcGroup {
            get {
                return ResourceManager.GetString("UnistackSvcGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载内核驱动 的本地化字符串。
        /// </summary>
        internal static string UnLoadDriver {
            get {
                return ResourceManager.GetString("UnLoadDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除文件占用失败 的本地化字符串。
        /// </summary>
        internal static string UnlockFileFailed {
            get {
                return ResourceManager.GetString("UnlockFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除文件占用成功 的本地化字符串。
        /// </summary>
        internal static string UnlockFileSuccess {
            get {
                return ResourceManager.GetString("UnlockFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利用率 的本地化字符串。
        /// </summary>
        internal static string Useage {
            get {
                return ResourceManager.GetString("Useage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户服务 的本地化字符串。
        /// </summary>
        internal static string UserService {
            get {
                return ResourceManager.GetString("UserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法枚举通用应用 的本地化字符串。
        /// </summary>
        internal static string UWPEnumFail {
            get {
                return ResourceManager.GetString("UWPEnumFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程 {0} [{1}] 的所有句柄：{2} 的本地化字符串。
        /// </summary>
        internal static string VHandleTitle {
            get {
                return ResourceManager.GetString("VHandleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可见 的本地化字符串。
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取文件夹 的本地化字符串。
        /// </summary>
        internal static string VisitFolderFailed {
            get {
                return ResourceManager.GetString("VisitFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程 %s [%d] 的所有模块：%d 的本地化字符串。
        /// </summary>
        internal static string VModulTitle {
            get {
                return ResourceManager.GetString("VModulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程 %s [%d] 的所有线程：%d 的本地化字符串。
        /// </summary>
        internal static string VThreadTitle {
            get {
                return ResourceManager.GetString("VThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程 %s [%d] 的所有窗口：%d 的本地化字符串。
        /// </summary>
        internal static string VWinTitle {
            get {
                return ResourceManager.GetString("VWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口类名 的本地化字符串。
        /// </summary>
        internal static string WindowClassName {
            get {
                return ResourceManager.GetString("WindowClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口句柄 的本地化字符串。
        /// </summary>
        internal static string WindowHandle {
            get {
                return ResourceManager.GetString("WindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口文字 的本地化字符串。
        /// </summary>
        internal static string WindowText {
            get {
                return ResourceManager.GetString("WindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入速度 的本地化字符串。
        /// </summary>
        internal static string WriteSpeed {
            get {
                return ResourceManager.GetString("WriteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///已经在您的软件目录下找到64位的 PCMgr ，点击”启动64位版本“可以直接启动软件。 的本地化字符串。
        /// </summary>
        internal static string X64WarnFinded64Text {
            get {
                return ResourceManager.GetString("X64WarnFinded64Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本的 PCMgr 是 32位的，而您的系统版本是64位的，一些高级功能（比如内核驱动查看）必须使用64位的驱动，所以此版本无法使用这些高级功能。 的本地化字符串。
        /// </summary>
        internal static string X64WarnMoreText {
            get {
                return ResourceManager.GetString("X64WarnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到您在64位系统中运行32位的 PCMgr ，这将导致某些功能不可用。您还要继续运行软件吗？ 的本地化字符串。
        /// </summary>
        internal static string X64WarnText {
            get {
                return ResourceManager.GetString("X64WarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到软件版本与系统版本不符 的本地化字符串。
        /// </summary>
        internal static string X64WarnTitle {
            get {
                return ResourceManager.GetString("X64WarnTitle", resourceCulture);
            }
        }
    }
}
