//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMgr.Lanuages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanuageResource_zh_Hant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanuageResource_zh_Hant() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCMgr.Lanuages.LanuageResource_zh-Hant", typeof(LanuageResource_zh_Hant).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 疑问 的本地化字符串。
        /// </summary>
        internal static string AskTitle {
            get {
                return ResourceManager.GetString("AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束进程(E) 的本地化字符串。
        /// </summary>
        internal static string BtnEndProcess {
            get {
                return ResourceManager.GetString("BtnEndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束任务(E) 的本地化字符串。
        /// </summary>
        internal static string BtnEndTask {
            get {
                return ResourceManager.GetString("BtnEndTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动(E) 的本地化字符串。
        /// </summary>
        internal static string BtnRestartText {
            get {
                return ResourceManager.GetString("BtnRestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消运行 的本地化字符串。
        /// </summary>
        internal static string CancelRun {
            get {
                return ResourceManager.GetString("CancelRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续运行 的本地化字符串。
        /// </summary>
        internal static string ContinueRun {
            get {
                return ResourceManager.GetString("ContinueRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动 的本地化字符串。
        /// </summary>
        internal static string DemandStart {
            get {
                return ResourceManager.GetString("DemandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不要再提醒我了 的本地化字符串。
        /// </summary>
        internal static string DoNotRemidMeLater {
            get {
                return ResourceManager.GetString("DoNotRemidMeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动加载 的本地化字符串。
        /// </summary>
        internal static string DriverLoad {
            get {
                return ResourceManager.GetString("DriverLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ErrTitle {
            get {
                return ResourceManager.GetString("ErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提权失败！ 的本地化字符串。
        /// </summary>
        internal static string FailedGetPrivileges {
            get {
                return ResourceManager.GetString("FailedGetPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FileCopyed {
            get {
                return ResourceManager.GetString("FileCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经剪切到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FileCuted {
            get {
                return ResourceManager.GetString("FileCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件系统 的本地化字符串。
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FolderCopyed {
            get {
                return ResourceManager.GetString("FolderCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已经剪切到剪贴板 的本地化字符串。
        /// </summary>
        internal static string FolderCuted {
            get {
                return ResourceManager.GetString("FolderCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的文件夹已经存在 的本地化字符串。
        /// </summary>
        internal static string FolderHasExist {
            get {
                return ResourceManager.GetString("FolderHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取失败 的本地化字符串。
        /// </summary>
        internal static string GetFailed {
            get {
                return ResourceManager.GetString("GetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名无效。 的本地化字符串。
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内核服务 的本地化字符串。
        /// </summary>
        internal static string KernelDriver {
            get {
                return ResourceManager.GetString("KernelDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置只有您重新打开软件才会生效 的本地化字符串。
        /// </summary>
        internal static string LanuageChangedTip {
            get {
                return ResourceManager.GetString("LanuageChangedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务 的本地化字符串。
        /// </summary>
        internal static string LocalService {
            get {
                return ResourceManager.GetString("LocalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务（模拟） 的本地化字符串。
        /// </summary>
        internal static string LocalServiceAndNoImpersonation {
            get {
                return ResourceManager.GetString("LocalServiceAndNoImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务（网络受限） 的本地化字符串。
        /// </summary>
        internal static string LocalServiceNetworkRestricted {
            get {
                return ResourceManager.GetString("LocalServiceNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地服务（无网络） 的本地化字符串。
        /// </summary>
        internal static string LocalServiceNoNetwork {
            get {
                return ResourceManager.GetString("LocalServiceNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地系统 的本地化字符串。
        /// </summary>
        internal static string LocalSystem {
            get {
                return ResourceManager.GetString("LocalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地系统（网络受限） 的本地化字符串。
        /// </summary>
        internal static string LocalSystemNetworkRestricted {
            get {
                return ResourceManager.GetString("LocalSystemNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件需要更多的权限... 的本地化字符串。
        /// </summary>
        internal static string NeedAdmin {
            get {
                return ResourceManager.GetString("NeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络服务 的本地化字符串。
        /// </summary>
        internal static string NetworkService {
            get {
                return ResourceManager.GetString("NetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络服务（模拟） 的本地化字符串。
        /// </summary>
        internal static string NetworkServiceAndNoImpersonation {
            get {
                return ResourceManager.GetString("NetworkServiceAndNoImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络服务（网络受限） 的本地化字符串。
        /// </summary>
        internal static string NetworkServiceNetworkRestricted {
            get {
                return ResourceManager.GetString("NetworkServiceNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹失败 的本地化字符串。
        /// </summary>
        internal static string NewFolderFailed {
            get {
                return ResourceManager.GetString("NewFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹成功 的本地化字符串。
        /// </summary>
        internal static string NewFolderSuccess {
            get {
                return ResourceManager.GetString("NewFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您想打开此文件吗？ 的本地化字符串。
        /// </summary>
        internal static string OpenAsk {
            get {
                return ResourceManager.GetString("OpenAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string PathCopyed {
            get {
                return ResourceManager.GetString("PathCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 :  的本地化字符串。
        /// </summary>
        internal static string PathStart {
            get {
                return ResourceManager.GetString("PathStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string PathUnExists {
            get {
                return ResourceManager.GetString("PathUnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要跳转的路径！ 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterPath {
            get {
                return ResourceManager.GetString("PleaseEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32位 的本地化字符串。
        /// </summary>
        internal static string Process32Bit {
            get {
                return ResourceManager.GetString("Process32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程数 的本地化字符串。
        /// </summary>
        internal static string ProcessCount {
            get {
                return ResourceManager.GetString("ProcessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪  共 的本地化字符串。
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个项目 的本地化字符串。
        /// </summary>
        internal static string ReadyStatusEnd {
            get {
                return ResourceManager.GetString("ReadyStatusEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个项目  选择了 的本地化字符串。
        /// </summary>
        internal static string ReadyStatusEnd2 {
            get {
                return ResourceManager.GetString("ReadyStatusEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到您没有赋予 PCMgr 管理员权限，这会导致一些高级功能不可用。\nPCMgr 需要管理员权限 才能对系统进行控制和管理。\n\n了解什么是&lt;A HREF=\&quot;#\&quot;&gt;管理员权限&lt;/A&gt;。\n了解本软件使用&lt;A HREF=\&quot;#\&quot;&gt;管理员权限控制和管理的详情&lt;/A&gt;。 的本地化字符串。
        /// </summary>
        internal static string RequestAdminText {
            get {
                return ResourceManager.GetString("RequestAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string RequestAdminTitle {
            get {
                return ResourceManager.GetString("RequestAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行64位版本 的本地化字符串。
        /// </summary>
        internal static string Run64 {
            get {
                return ResourceManager.GetString("Run64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以管理员身份重启软件 的本地化字符串。
        /// </summary>
        internal static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务数 的本地化字符串。
        /// </summary>
        internal static string ServiceCount {
            get {
                return ResourceManager.GetString("ServiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务主机 的本地化字符串。
        /// </summary>
        internal static string ServiceHost {
            get {
                return ResourceManager.GetString("ServiceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动服务管理器 的本地化字符串。
        /// </summary>
        internal static string StartSCMFailed {
            get {
                return ResourceManager.GetString("StartSCMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无响应 的本地化字符串。
        /// </summary>
        internal static string StatusHang {
            get {
                return ResourceManager.GetString("StatusHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行 的本地化字符串。
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统空闲进程 的本地化字符串。
        /// </summary>
        internal static string SystemIdleProcess {
            get {
                return ResourceManager.GetString("SystemIdleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统服务 的本地化字符串。
        /// </summary>
        internal static string SystemService {
            get {
                return ResourceManager.GetString("SystemService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string TipTitle {
            get {
                return ResourceManager.GetString("TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台进程 的本地化字符串。
        /// </summary>
        internal static string TitleBackGround {
            get {
                return ResourceManager.GetString("TitleBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基地址 的本地化字符串。
        /// </summary>
        internal static string TitleBaseAddress {
            get {
                return ResourceManager.GetString("TitleBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令行 的本地化字符串。
        /// </summary>
        internal static string TitleCmdLine {
            get {
                return ResourceManager.GetString("TitleCmdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定继续吗？ 的本地化字符串。
        /// </summary>
        internal static string TitleContinue {
            get {
                return ResourceManager.GetString("TitleContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘 的本地化字符串。
        /// </summary>
        internal static string TitleDisk {
            get {
                return ResourceManager.GetString("TitleDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载顺序 的本地化字符串。
        /// </summary>
        internal static string TitleDriverLoadPath {
            get {
                return ResourceManager.GetString("TitleDriverLoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动名称 的本地化字符串。
        /// </summary>
        internal static string TitleDriverName {
            get {
                return ResourceManager.GetString("TitleDriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动对象 的本地化字符串。
        /// </summary>
        internal static string TitleDriverObj {
            get {
                return ResourceManager.GetString("TitleDriverObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动路径 的本地化字符串。
        /// </summary>
        internal static string TitleDriverPath {
            get {
                return ResourceManager.GetString("TitleDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务名 的本地化字符串。
        /// </summary>
        internal static string TitleDriverScName {
            get {
                return ResourceManager.GetString("TitleDriverScName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string TitleDriverSize {
            get {
                return ResourceManager.GetString("TitleDriverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完整名称 的本地化字符串。
        /// </summary>
        internal static string TitleFullName {
            get {
                return ResourceManager.GetString("TitleFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装路径 的本地化字符串。
        /// </summary>
        internal static string TitleInstallDir {
            get {
                return ResourceManager.GetString("TitleInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将注销。 的本地化字符串。
        /// </summary>
        internal static string TitleLogoOff {
            get {
                return ResourceManager.GetString("TitleLogoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        internal static string TitleNet {
            get {
                return ResourceManager.GetString("TitleNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程名称 的本地化字符串。
        /// </summary>
        internal static string TitleProcName {
            get {
                return ResourceManager.GetString("TitleProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程路径 的本地化字符串。
        /// </summary>
        internal static string TitleProcPath {
            get {
                return ResourceManager.GetString("TitleProcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布者 的本地化字符串。
        /// </summary>
        internal static string TitlePublisher {
            get {
                return ResourceManager.GetString("TitlePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存 的本地化字符串。
        /// </summary>
        internal static string TitleRam {
            get {
                return ResourceManager.GetString("TitleRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将重启。 的本地化字符串。
        /// </summary>
        internal static string TitleReboot {
            get {
                return ResourceManager.GetString("TitleReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将重启。 的本地化字符串。
        /// </summary>
        internal static string TitleRestart {
            get {
                return ResourceManager.GetString("TitleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您即将关机 的本地化字符串。
        /// </summary>
        internal static string TitleShutdown {
            get {
                return ResourceManager.GetString("TitleShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string TitleStatus {
            get {
                return ResourceManager.GetString("TitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows进程 的本地化字符串。
        /// </summary>
        internal static string TitleWinApp {
            get {
                return ResourceManager.GetString("TitleWinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unistack 服务组 的本地化字符串。
        /// </summary>
        internal static string UnistackSvcGroup {
            get {
                return ResourceManager.GetString("UnistackSvcGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户服务 的本地化字符串。
        /// </summary>
        internal static string UserService {
            get {
                return ResourceManager.GetString("UserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法枚举通用应用 的本地化字符串。
        /// </summary>
        internal static string UWPEnumFail {
            get {
                return ResourceManager.GetString("UWPEnumFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取文件夹 的本地化字符串。
        /// </summary>
        internal static string VisitFolderFailed {
            get {
                return ResourceManager.GetString("VisitFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \n已经在您的软件目录下找到64位的 PCMgr ，点击”启动64位版本“可以直接启动软件。 的本地化字符串。
        /// </summary>
        internal static string X64WarnFinded64Text {
            get {
                return ResourceManager.GetString("X64WarnFinded64Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本的 PCMgr 是 32位的，而您的系统版本是64位的，一些高级功能（比如内核驱动查看）必须使用64位的驱动，所以此版本无法使用这些高级功能。 的本地化字符串。
        /// </summary>
        internal static string X64WarnMoreText {
            get {
                return ResourceManager.GetString("X64WarnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到您在64位系统中运行32位的 PCMgr ，这将导致某些功能不可用。您还要继续运行软件吗？ 的本地化字符串。
        /// </summary>
        internal static string X64WarnText {
            get {
                return ResourceManager.GetString("X64WarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到软件版本与系统版本不符 的本地化字符串。
        /// </summary>
        internal static string X64WarnTitle {
            get {
                return ResourceManager.GetString("X64WarnTitle", resourceCulture);
            }
        }
    }
}
