//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMgr.Lanuages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanuageResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanuageResource_en() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCMgr.Lanuages.LanuageResource_en", typeof(LanuageResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Access Denied 的本地化字符串。
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active time 的本地化字符串。
        /// </summary>
        internal static string ActiveTime {
            get {
                return ResourceManager.GetString("ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCMgr 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        internal static string AskTitle {
            get {
                return ResourceManager.GetString("AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Start 的本地化字符串。
        /// </summary>
        internal static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Thread 的本地化字符串。
        /// </summary>
        internal static string BelongThread {
            get {
                return ResourceManager.GetString("BelongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;End Process 的本地化字符串。
        /// </summary>
        internal static string BtnEndProcess {
            get {
                return ResourceManager.GetString("BtnEndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;End Task 的本地化字符串。
        /// </summary>
        internal static string BtnEndTask {
            get {
                return ResourceManager.GetString("BtnEndTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart (E) 的本地化字符串。
        /// </summary>
        internal static string BtnRestartText {
            get {
                return ResourceManager.GetString("BtnRestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Cache : 的本地化字符串。
        /// </summary>
        internal static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cached 的本地化字符串。
        /// </summary>
        internal static string Cached {
            get {
                return ResourceManager.GetString("Cached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelRun {
            get {
                return ResourceManager.GetString("CancelRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy file failed. 的本地化字符串。
        /// </summary>
        internal static string CantCopyFile {
            get {
                return ResourceManager.GetString("CantCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get process failed 的本地化字符串。
        /// </summary>
        internal static string CantGetPath {
            get {
                return ResourceManager.GetString("CantGetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move file failed. 的本地化字符串。
        /// </summary>
        internal static string CantMoveFile {
            get {
                return ResourceManager.GetString("CantMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You change the window text, to set the text to the window? 的本地化字符串。
        /// </summary>
        internal static string ChangeWindowTextAsk {
            get {
                return ResourceManager.GetString("ChangeWindowTextAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose target directory 的本地化字符串。
        /// </summary>
        internal static string ChooseTargetDir {
            get {
                return ResourceManager.GetString("ChooseTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculating the files need to delete... 的本地化字符串。
        /// </summary>
        internal static string CollectingFiles {
            get {
                return ResourceManager.GetString("CollectingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Context Switch time 的本地化字符串。
        /// </summary>
        internal static string ContextSwitch {
            get {
                return ResourceManager.GetString("ContextSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        internal static string ContinueRun {
            get {
                return ResourceManager.GetString("ContinueRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copying files 的本地化字符串。
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logic processors : 的本地化字符串。
        /// </summary>
        internal static string CpuCpunt {
            get {
                return ResourceManager.GetString("CpuCpunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cpu packages : 的本地化字符串。
        /// </summary>
        internal static string CpuPackageCount {
            get {
                return ResourceManager.GetString("CpuPackageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete this file? 的本地化字符串。
        /// </summary>
        internal static string DelAsk1 {
            get {
                return ResourceManager.GetString("DelAsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete these %d files? 的本地化字符串。
        /// </summary>
        internal static string DelAsk2 {
            get {
                return ResourceManager.GetString("DelAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete this folder? 的本地化字符串。
        /// </summary>
        internal static string DelAsk3 {
            get {
                return ResourceManager.GetString("DelAsk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting... 的本地化字符串。
        /// </summary>
        internal static string DeleteFiles {
            get {
                return ResourceManager.GetString("DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete in... 的本地化字符串。
        /// </summary>
        internal static string DeleteIng {
            get {
                return ResourceManager.GetString("DeleteIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete failed 的本地化字符串。
        /// </summary>
        internal static string DelFailed {
            get {
                return ResourceManager.GetString("DelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting this startup is not recoverable, and you need to determine that the startup item is not a system must, otherwise the deletion may cause the problem to run normally on your system. 的本地化字符串。
        /// </summary>
        internal static string DelStartupItemAsk {
            get {
                return ResourceManager.GetString("DelStartupItemAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this startup item and the file is not recoverable. You need to make sure that the file is not a system required file. Otherwise, the deletion may cause damage to your system. 的本地化字符串。
        /// </summary>
        internal static string DelStartupItemAsk2 {
            get {
                return ResourceManager.GetString("DelStartupItemAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete confirmation 的本地化字符串。
        /// </summary>
        internal static string DelSure {
            get {
                return ResourceManager.GetString("DelSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demand Start 的本地化字符串。
        /// </summary>
        internal static string DemandStart {
            get {
                return ResourceManager.GetString("DemandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t remind me again 的本地化字符串。
        /// </summary>
        internal static string DoNotRemidMeLater {
            get {
                return ResourceManager.GetString("DoNotRemidMeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver count : 的本地化字符串。
        /// </summary>
        internal static string DriverCount {
            get {
                return ResourceManager.GetString("DriverCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded driver :  的本地化字符串。
        /// </summary>
        internal static string DriverCountLoaded {
            get {
                return ResourceManager.GetString("DriverCountLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DriverLoad 的本地化字符串。
        /// </summary>
        internal static string DriverLoad {
            get {
                return ResourceManager.GetString("DriverLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Load failed, Lset Error : {0} . for more information, please see in debug output window. 的本地化字符串。
        /// </summary>
        internal static string DriverLoadFailed {
            get {
                return ResourceManager.GetString("DriverLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Load Success. 的本地化字符串。
        /// </summary>
        internal static string DriverLoadSuccessFull {
            get {
                return ResourceManager.GetString("DriverLoadSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver unoad failed, Lset Error : {0} . for more information, please see in debug output window. 的本地化字符串。
        /// </summary>
        internal static string DriverUnLoadFailed {
            get {
                return ResourceManager.GetString("DriverUnLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver UnLoad Success. 的本地化字符串。
        /// </summary>
        internal static string DriverUnLoadSuccessFull {
            get {
                return ResourceManager.GetString("DriverUnLoadSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End process failed 的本地化字符串。
        /// </summary>
        internal static string EndProcFailed {
            get {
                return ResourceManager.GetString("EndProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry Point 的本地化字符串。
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Enum Module 的本地化字符串。
        /// </summary>
        internal static string EnumModuleFailed {
            get {
                return ResourceManager.GetString("EnumModuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Enum Thread 的本地化字符串。
        /// </summary>
        internal static string EnumThreadFailed {
            get {
                return ResourceManager.GetString("EnumThreadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ErrTitle {
            get {
                return ResourceManager.GetString("ErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Get Privileges! 的本地化字符串。
        /// </summary>
        internal static string FailedGetPrivileges {
            get {
                return ResourceManager.GetString("FailedGetPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file has been copied to the clipboard 的本地化字符串。
        /// </summary>
        internal static string FileCopyed {
            get {
                return ResourceManager.GetString("FileCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file has been cut to the clipboard 的本地化字符串。
        /// </summary>
        internal static string FileCuted {
            get {
                return ResourceManager.GetString("FileCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File already exists 的本地化字符串。
        /// </summary>
        internal static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File have already exists, cover it ? 的本地化字符串。
        /// </summary>
        internal static string FileExist2 {
            get {
                return ResourceManager.GetString("FileExist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not exist. 的本地化字符串。
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not sign. 的本地化字符串。
        /// </summary>
        internal static string FileNotTrust {
            get {
                return ResourceManager.GetString("FileNotTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileSystem 的本地化字符串。
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File have signed.
        ///
        ///&lt;A HREF=&quot;#&quot;&gt;View the certificate&lt;/A&gt; 的本地化字符串。
        /// </summary>
        internal static string FileTrust {
            get {
                return ResourceManager.GetString("FileTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill file failed. 的本地化字符串。
        /// </summary>
        internal static string FillFileFailed {
            get {
                return ResourceManager.GetString("FillFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file size can not be 0 ! 的本地化字符串。
        /// </summary>
        internal static string FillFileNeedSize {
            get {
                return ResourceManager.GetString("FillFileNeedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill file success. 的本地化字符串。
        /// </summary>
        internal static string FillFileSuccess {
            get {
                return ResourceManager.GetString("FillFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder has been copied to the clipboard 的本地化字符串。
        /// </summary>
        internal static string FolderCopyed {
            get {
                return ResourceManager.GetString("FolderCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder has been cut to the clipboard 的本地化字符串。
        /// </summary>
        internal static string FolderCuted {
            get {
                return ResourceManager.GetString("FolderCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified folder already exists 的本地化字符串。
        /// </summary>
        internal static string FolderHasExist {
            get {
                return ResourceManager.GetString("FolderHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free module failed 的本地化字符串。
        /// </summary>
        internal static string FreeFailed {
            get {
                return ResourceManager.GetString("FreeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to Free module,  the process has exited. 的本地化字符串。
        /// </summary>
        internal static string FreeInvalidProc {
            get {
                return ResourceManager.GetString("FreeInvalidProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free success. 的本地化字符串。
        /// </summary>
        internal static string FreeLibSuccess {
            get {
                return ResourceManager.GetString("FreeLibSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Froce delete Succeed. 的本地化字符串。
        /// </summary>
        internal static string FroceDelSuccess {
            get {
                return ResourceManager.GetString("FroceDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Failed 的本地化字符串。
        /// </summary>
        internal static string GetFailed {
            get {
                return ResourceManager.GetString("GetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed get file info. 的本地化字符串。
        /// </summary>
        internal static string GetFileInfoFailed {
            get {
                return ResourceManager.GetString("GetFileInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle Count 的本地化字符串。
        /// </summary>
        internal static string HandleCount {
            get {
                return ResourceManager.GetString("HandleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid file name. 的本地化字符串。
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Hwnd. 的本地化字符串。
        /// </summary>
        internal static string InvalidHwnd {
            get {
                return ResourceManager.GetString("InvalidHwnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Process. 的本地化字符串。
        /// </summary>
        internal static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid thread. 的本地化字符串。
        /// </summary>
        internal static string InvThread {
            get {
                return ResourceManager.GetString("InvThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KernelDriver 的本地化字符串。
        /// </summary>
        internal static string KernelDriver {
            get {
                return ResourceManager.GetString("KernelDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kernel driver not load. 的本地化字符串。
        /// </summary>
        internal static string KernelNotLoad {
            get {
                return ResourceManager.GetString("KernelNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If an open program is associated with this process, it will close the program and lose all unsaved data. If you end a system process, you may cause the system to be unstable. Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string KillAskContent {
            get {
                return ResourceManager.GetString("KillAskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ? 的本地化字符串。
        /// </summary>
        internal static string KillAskEnd {
            get {
                return ResourceManager.GetString("KillAskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to kill  的本地化字符串。
        /// </summary>
        internal static string KillAskStart {
            get {
                return ResourceManager.GetString("KillAskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to terminate process. 的本地化字符串。
        /// </summary>
        internal static string KillFailed {
            get {
                return ResourceManager.GetString("KillFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not terminate last PCMgr process , you can terminate by your self. 的本地化字符串。
        /// </summary>
        internal static string KillOldFailed {
            get {
                return ResourceManager.GetString("KillOldFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The last PCMgr process has terminated. 的本地化字符串。
        /// </summary>
        internal static string KillOldSuccess {
            get {
                return ResourceManager.GetString("KillOldSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to Terminate thread 的本地化字符串。
        /// </summary>
        internal static string KillThreadError {
            get {
                return ResourceManager.GetString("KillThreadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to Terminate thread, invalid thread. 的本地化字符串。
        /// </summary>
        internal static string KillThreadInvThread {
            get {
                return ResourceManager.GetString("KillThreadInvThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language settings will only take effect when you open the software next time. 的本地化字符串。
        /// </summary>
        internal static string LanuageChangedTip {
            get {
                return ResourceManager.GetString("LanuageChangedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load kernel driver 的本地化字符串。
        /// </summary>
        internal static string LoadDriver {
            get {
                return ResourceManager.GetString("LoadDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load kernel driver! 的本地化字符串。
        /// </summary>
        internal static string LoadDriverErr {
            get {
                return ResourceManager.GetString("LoadDriverErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Service 的本地化字符串。
        /// </summary>
        internal static string LocalService {
            get {
                return ResourceManager.GetString("LocalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Service (And No Impersonation) 的本地化字符串。
        /// </summary>
        internal static string LocalServiceAndNoImpersonation {
            get {
                return ResourceManager.GetString("LocalServiceAndNoImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Service (Network Restricted) 的本地化字符串。
        /// </summary>
        internal static string LocalServiceNetworkRestricted {
            get {
                return ResourceManager.GetString("LocalServiceNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Service (No Network) 的本地化字符串。
        /// </summary>
        internal static string LocalServiceNoNetwork {
            get {
                return ResourceManager.GetString("LocalServiceNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local System 的本地化字符串。
        /// </summary>
        internal static string LocalSystem {
            get {
                return ResourceManager.GetString("LocalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local System (Network Restricted) 的本地化字符串。
        /// </summary>
        internal static string LocalSystemNetworkRestricted {
            get {
                return ResourceManager.GetString("LocalSystemNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum speed :  的本地化字符串。
        /// </summary>
        internal static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In use 的本地化字符串。
        /// </summary>
        internal static string MemUsing {
            get {
                return ResourceManager.GetString("MemUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available 的本地化字符串。
        /// </summary>
        internal static string MenCanUse {
            get {
                return ResourceManager.GetString("MenCanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart as administrator 的本地化字符串。
        /// </summary>
        internal static string MenuRebootAsAdmin {
            get {
                return ResourceManager.GetString("MenuRebootAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Name 的本地化字符串。
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Path 的本地化字符串。
        /// </summary>
        internal static string ModulePath {
            get {
                return ResourceManager.GetString("ModulePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving the file... 的本地化字符串。
        /// </summary>
        internal static string Moveing {
            get {
                return ResourceManager.GetString("Moveing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software needs more permissions... 的本地化字符串。
        /// </summary>
        internal static string NeedAdmin {
            get {
                return ResourceManager.GetString("NeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Service 的本地化字符串。
        /// </summary>
        internal static string NetworkService {
            get {
                return ResourceManager.GetString("NetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Service (And No Impersonation) 的本地化字符串。
        /// </summary>
        internal static string NetworkServiceAndNoImpersonation {
            get {
                return ResourceManager.GetString("NetworkServiceAndNoImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Service (Network Restricted) 的本地化字符串。
        /// </summary>
        internal static string NetworkServiceNetworkRestricted {
            get {
                return ResourceManager.GetString("NetworkServiceNetworkRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New folder 的本地化字符串。
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New folder failed 的本地化字符串。
        /// </summary>
        internal static string NewFolderFailed {
            get {
                return ResourceManager.GetString("NewFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New folder succeed 的本地化字符串。
        /// </summary>
        internal static string NewFolderSuccess {
            get {
                return ResourceManager.GetString("NewFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select &quot;Yes&quot; or &quot;OK&quot; to give the program administrator permission in the dialog box just now. 的本地化字符串。
        /// </summary>
        internal static string NoAdminTipText {
            get {
                return ResourceManager.GetString("NoAdminTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You refuse to give permission. 的本地化字符串。
        /// </summary>
        internal static string NoAdminTipTitle {
            get {
                return ResourceManager.GetString("NoAdminTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-paged pool 的本地化字符串。
        /// </summary>
        internal static string NonPagedPool {
            get {
                return ResourceManager.GetString("NonPagedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to open this file? 的本地化字符串。
        /// </summary>
        internal static string OpenAsk {
            get {
                return ResourceManager.GetString("OpenAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open the process 的本地化字符串。
        /// </summary>
        internal static string OpenProcFailed {
            get {
                return ResourceManager.GetString("OpenProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open thread 的本地化字符串。
        /// </summary>
        internal static string OpenThreadFailed {
            get {
                return ResourceManager.GetString("OpenThreadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to complete this operation 的本地化字符串。
        /// </summary>
        internal static string OpFailed {
            get {
                return ResourceManager.GetString("OpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success. 的本地化字符串。
        /// </summary>
        internal static string OpSuccess {
            get {
                return ResourceManager.GetString("OpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paged pool 的本地化字符串。
        /// </summary>
        internal static string PagedPool {
            get {
                return ResourceManager.GetString("PagedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path has been copied to the clipboard 的本地化字符串。
        /// </summary>
        internal static string PathCopyed {
            get {
                return ResourceManager.GetString("PathCopyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path :  的本地化字符串。
        /// </summary>
        internal static string PathStart {
            get {
                return ResourceManager.GetString("PathStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path does not exist! 的本地化字符串。
        /// </summary>
        internal static string PathUnExists {
            get {
                return ResourceManager.GetString("PathUnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose a driver and load！ 的本地化字符串。
        /// </summary>
        internal static string PleaseChooseDriver {
            get {
                return ResourceManager.GetString("PleaseChooseDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter Driver ServiceName 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterDriverServiceName {
            get {
                return ResourceManager.GetString("PleaseEnterDriverServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the path to go! 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterPath {
            get {
                return ResourceManager.GetString("PleaseEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 32 Bit 的本地化字符串。
        /// </summary>
        internal static string Process32Bit {
            get {
                return ResourceManager.GetString("Process32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Count 的本地化字符串。
        /// </summary>
        internal static string ProcessCount {
            get {
                return ResourceManager.GetString("ProcessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue time 的本地化字符串。
        /// </summary>
        internal static string QueueTime {
            get {
                return ResourceManager.GetString("QueueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read speed 的本地化字符串。
        /// </summary>
        internal static string ReadSpeed {
            get {
                return ResourceManager.GetString("ReadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready  的本地化字符串。
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  files 的本地化字符串。
        /// </summary>
        internal static string ReadyStatusEnd {
            get {
                return ResourceManager.GetString("ReadyStatusEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  files  choosed  的本地化字符串。
        /// </summary>
        internal static string ReadyStatusEnd2 {
            get {
                return ResourceManager.GetString("ReadyStatusEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive 的本地化字符串。
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh successfuly. 的本地化字符串。
        /// </summary>
        internal static string RefeshSuccess {
            get {
                return ResourceManager.GetString("RefeshSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is detected that you did not grant PCMgr administrator permission, which could result in some advanced functions unavailable. 
        ///PCMgr requires administrator authority to control and manage the system. 
        ///knows what &lt;A HREF=&quot;#&quot;&gt; administrator authority &lt;/A&gt;. 
        ///understand the details of the software using &lt;A HREF=&quot;#&quot;&gt; administrator rights control and management.&lt;/A&gt; 的本地化字符串。
        /// </summary>
        internal static string RequestAdminText {
            get {
                return ResourceManager.GetString("RequestAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I need more permissions 的本地化字符串。
        /// </summary>
        internal static string RequestAdminTitle {
            get {
                return ResourceManager.GetString("RequestAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to resume process 的本地化字符串。
        /// </summary>
        internal static string ResProcFailed {
            get {
                return ResourceManager.GetString("ResProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to resume thread 的本地化字符串。
        /// </summary>
        internal static string ReThreadErr {
            get {
                return ResourceManager.GetString("ReThreadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminate last PCMgr process 的本地化字符串。
        /// </summary>
        internal static string Run2KillOld {
            get {
                return ResourceManager.GetString("Run2KillOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is detected that you have run a PCMgr and not close it. Running multiple PCMgr may cause software function to be abnormal. 
        ///If the last program is stuck or unresponsive, you can also choose to Terminate the last process. 的本地化字符串。
        /// </summary>
        internal static string Run2WarnText {
            get {
                return ResourceManager.GetString("Run2WarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 64 - bit version 的本地化字符串。
        /// </summary>
        internal static string Run64 {
            get {
                return ResourceManager.GetString("Run64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot the software as an administrator 的本地化字符串。
        /// </summary>
        internal static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up time 的本地化字符串。
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 s 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Count 的本地化字符串。
        /// </summary>
        internal static string ServiceCount {
            get {
                return ResourceManager.GetString("ServiceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Host 的本地化字符串。
        /// </summary>
        internal static string ServiceHost {
            get {
                return ResourceManager.GetString("ServiceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to start the service manager 的本地化字符串。
        /// </summary>
        internal static string StartSCMFailed {
            get {
                return ResourceManager.GetString("StartSCMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not response 的本地化字符串。
        /// </summary>
        internal static string StatusHang {
            get {
                return ResourceManager.GetString("StatusHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        internal static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Committed 的本地化字符串。
        /// </summary>
        internal static string Submited {
            get {
                return ResourceManager.GetString("Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to suspend process 的本地化字符串。
        /// </summary>
        internal static string SusProcFailed {
            get {
                return ResourceManager.GetString("SusProcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to suspend thread 的本地化字符串。
        /// </summary>
        internal static string SuThreadErr {
            get {
                return ResourceManager.GetString("SuThreadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not recommended to force threads to hang up, because suspending threads are prone to other problems such as life and death locks. If you are not debugging programs, do not use this method. 
        ///Then, make sure that the thread is forced to hang? 的本地化字符串。
        /// </summary>
        internal static string SuThreadWarn {
            get {
                return ResourceManager.GetString("SuThreadWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Idle Process 的本地化字符串。
        /// </summary>
        internal static string SystemIdleProcess {
            get {
                return ResourceManager.GetString("SystemIdleProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Service 的本地化字符串。
        /// </summary>
        internal static string SystemService {
            get {
                return ResourceManager.GetString("SystemService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thread Count 的本地化字符串。
        /// </summary>
        internal static string ThreadCount {
            get {
                return ResourceManager.GetString("ThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        internal static string TipTitle {
            get {
                return ResourceManager.GetString("TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apps 的本地化字符串。
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background processes 的本地化字符串。
        /// </summary>
        internal static string TitleBackGround {
            get {
                return ResourceManager.GetString("TitleBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base adress 的本地化字符串。
        /// </summary>
        internal static string TitleBaseAddress {
            get {
                return ResourceManager.GetString("TitleBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Line 的本地化字符串。
        /// </summary>
        internal static string TitleCmdLine {
            get {
                return ResourceManager.GetString("TitleCmdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is it sure to continue? 的本地化字符串。
        /// </summary>
        internal static string TitleContinue {
            get {
                return ResourceManager.GetString("TitleContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU 的本地化字符串。
        /// </summary>
        internal static string TitleCPU {
            get {
                return ResourceManager.GetString("TitleCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 的本地化字符串。
        /// </summary>
        internal static string TitleDisk {
            get {
                return ResourceManager.GetString("TitleDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laod Order 的本地化字符串。
        /// </summary>
        internal static string TitleDriverLoadPath {
            get {
                return ResourceManager.GetString("TitleDriverLoadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Name 的本地化字符串。
        /// </summary>
        internal static string TitleDriverName {
            get {
                return ResourceManager.GetString("TitleDriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Obj 的本地化字符串。
        /// </summary>
        internal static string TitleDriverObj {
            get {
                return ResourceManager.GetString("TitleDriverObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Path 的本地化字符串。
        /// </summary>
        internal static string TitleDriverPath {
            get {
                return ResourceManager.GetString("TitleDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Service Name 的本地化字符串。
        /// </summary>
        internal static string TitleDriverScName {
            get {
                return ResourceManager.GetString("TitleDriverScName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Size 的本地化字符串。
        /// </summary>
        internal static string TitleDriverSize {
            get {
                return ResourceManager.GetString("TitleDriverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPROCESS 的本地化字符串。
        /// </summary>
        internal static string TitleEProcess {
            get {
                return ResourceManager.GetString("TitleEProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path 的本地化字符串。
        /// </summary>
        internal static string TitleFilePath {
            get {
                return ResourceManager.GetString("TitleFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determine the compulsory restart? The work you have not saved will be lost! 的本地化字符串。
        /// </summary>
        internal static string TitleFRebbot {
            get {
                return ResourceManager.GetString("TitleFRebbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure want to force shutdown? The work you have not saved will be lost! 的本地化字符串。
        /// </summary>
        internal static string TitleFShutdown {
            get {
                return ResourceManager.GetString("TitleFShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full name 的本地化字符串。
        /// </summary>
        internal static string TitleFullName {
            get {
                return ResourceManager.GetString("TitleFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Dir 的本地化字符串。
        /// </summary>
        internal static string TitleInstallDir {
            get {
                return ResourceManager.GetString("TitleInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You will be log off. 的本地化字符串。
        /// </summary>
        internal static string TitleLogoOff {
            get {
                return ResourceManager.GetString("TitleLogoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        internal static string TitleNet {
            get {
                return ResourceManager.GetString("TitleNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PID 的本地化字符串。
        /// </summary>
        internal static string TitlePID {
            get {
                return ResourceManager.GetString("TitlePID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process name 的本地化字符串。
        /// </summary>
        internal static string TitleProcName {
            get {
                return ResourceManager.GetString("TitleProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process path 的本地化字符串。
        /// </summary>
        internal static string TitleProcPath {
            get {
                return ResourceManager.GetString("TitleProcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publisher 的本地化字符串。
        /// </summary>
        internal static string TitlePublisher {
            get {
                return ResourceManager.GetString("TitlePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        internal static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ram 的本地化字符串。
        /// </summary>
        internal static string TitleRam {
            get {
                return ResourceManager.GetString("TitleRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Computer will be reboot. 的本地化字符串。
        /// </summary>
        internal static string TitleReboot {
            get {
                return ResourceManager.GetString("TitleReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry path 的本地化字符串。
        /// </summary>
        internal static string TitleRegPath {
            get {
                return ResourceManager.GetString("TitleRegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Computer will be restart. 的本地化字符串。
        /// </summary>
        internal static string TitleRestart {
            get {
                return ResourceManager.GetString("TitleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Computer will be shutdown. 的本地化字符串。
        /// </summary>
        internal static string TitleShutdown {
            get {
                return ResourceManager.GetString("TitleShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string TitleStatus {
            get {
                return ResourceManager.GetString("TitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Process 的本地化字符串。
        /// </summary>
        internal static string TitleWinApp {
            get {
                return ResourceManager.GetString("TitleWinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unistack Service Group 的本地化字符串。
        /// </summary>
        internal static string UnistackSvcGroup {
            get {
                return ResourceManager.GetString("UnistackSvcGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnLoad kernel driver 的本地化字符串。
        /// </summary>
        internal static string UnLoadDriver {
            get {
                return ResourceManager.GetString("UnLoadDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock file failed. 的本地化字符串。
        /// </summary>
        internal static string UnlockFileFailed {
            get {
                return ResourceManager.GetString("UnlockFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock file successed. 的本地化字符串。
        /// </summary>
        internal static string UnlockFileSuccess {
            get {
                return ResourceManager.GetString("UnlockFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Useage 的本地化字符串。
        /// </summary>
        internal static string Useage {
            get {
                return ResourceManager.GetString("Useage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Service 的本地化字符串。
        /// </summary>
        internal static string UserService {
            get {
                return ResourceManager.GetString("UserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to enumerate Universal applications 的本地化字符串。
        /// </summary>
        internal static string UWPEnumFail {
            get {
                return ResourceManager.GetString("UWPEnumFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process {0}[{1}] All handles : {2} 的本地化字符串。
        /// </summary>
        internal static string VHandleTitle {
            get {
                return ResourceManager.GetString("VHandleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open folder 的本地化字符串。
        /// </summary>
        internal static string VisitFolderFailed {
            get {
                return ResourceManager.GetString("VisitFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process : %s [%d] All modules : %d 的本地化字符串。
        /// </summary>
        internal static string VModulTitle {
            get {
                return ResourceManager.GetString("VModulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All threads of the process %s [%d]: %d 的本地化字符串。
        /// </summary>
        internal static string VThreadTitle {
            get {
                return ResourceManager.GetString("VThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process : %s [%d] All windows : %d 的本地化字符串。
        /// </summary>
        internal static string VWinTitle {
            get {
                return ResourceManager.GetString("VWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Class Name 的本地化字符串。
        /// </summary>
        internal static string WindowClassName {
            get {
                return ResourceManager.GetString("WindowClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Handle 的本地化字符串。
        /// </summary>
        internal static string WindowHandle {
            get {
                return ResourceManager.GetString("WindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Text 的本地化字符串。
        /// </summary>
        internal static string WindowText {
            get {
                return ResourceManager.GetString("WindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write speed 的本地化字符串。
        /// </summary>
        internal static string WriteSpeed {
            get {
                return ResourceManager.GetString("WriteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///has found 64 bits of PCMgr in your software directory, clicking &quot;start the 64 bit version&quot;, you can start the software directly. 的本地化字符串。
        /// </summary>
        internal static string X64WarnFinded64Text {
            get {
                return ResourceManager.GetString("X64WarnFinded64Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current version of PCMgr is 32 - bit, and your system version is 64 - bit, and some advanced features, such as kernel - driven view, must use a 64 bit driver, so this version can&apos;t use these advanced functions. 的本地化字符串。
        /// </summary>
        internal static string X64WarnMoreText {
            get {
                return ResourceManager.GetString("X64WarnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is detected that you run 32 bit PCMgr in the 64 bit system, which will result in some functions unavailable. Do you want to continue to run the software? 的本地化字符串。
        /// </summary>
        internal static string X64WarnText {
            get {
                return ResourceManager.GetString("X64WarnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The software version is not in conformity with the system version 的本地化字符串。
        /// </summary>
        internal static string X64WarnTitle {
            get {
                return ResourceManager.GetString("X64WarnTitle", resourceCulture);
            }
        }
    }
}
