//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TaskMgrCore.rc 使用
//
#define IDR_MENUMAIN                    101
#define IDD_ABOUTBOX                    102
#define IDI_ICONAPP                     104
#define IDI_ICONDEFAPP                  105
#define IDD_VTHEADS                     106
#define IDI_ICONHIDEDWIN                107
#define IDR_MENUWINMAIN                 108
#define IDR_MENUFMMAIN                  109
#define IDR_MENUFMFOLDER                110
#define IDR_MENUSCSMALL                 111
#define IDR_MENUSCMAIN                  112
#define IDR_MENUSTART                   113
#define IDR_MENUDRIVER                  114
#define IDI_ICONOPEN                    115
#define IDI_ICONSHUTDOWN                116
#define IDI_ICONLOGON                   117
#define IDR_MENUTASK                    118
#define IDI_ICONCONSOLE                 118
#define IDR_MENUSIMPPROC                119
#define IDS_STRING_RUN2TITLE            120
#define IDS_STRING_RUN2TEXT             121
#define IDR_MENUUSER                    121
#define IDS_STRING_CONRUN               122
#define IDS_STRING_MISSING_MAINDLL 130
#define IDD_CONNECTSESS                 131
#define IDS_STRING_CANRUN               123
#define IDS_STRING_KILLOLD              124
#define IDD_STATS                       124
#define IDD_VWINS                       125
#define IDS_STRING_MISSINGDLL_HLP       132
#define IDS_STRING_KILLOLDFAILED        126
#define IDD_PEVIEW                      127
#define IDS_STRING_LOADAPP_FAIL         127
#define IDD_CREATEDUMP                  129
#define IDI_ICONACTIVEDWIN              206
#define IDR_WINSMENU                    209
#define IDR_MODULSMENU                  214
#define IDD_VMODULS                     232
#define IDR_THREADMENU                  304
#define IDC_EDIT                        1001
#define IDC_THREADLIST                  1002
#define IDC_USERNAME                    1002
#define IDC_STAT_MEM                    1004
#define IDC_STAT_GC                     1005
#define IDC_FORCEGC                     1006
#define IDC_MODULLIST                   1007
#define IDC_STAT_AC_MEM                 1007
#define IDC_STAT_FREEMEM                1008
#define IDC_TITLE                       1009
#define IDC_STAT_INUSEMEM               1009
#define IDC_STAT_ACLLMEM                1010
#define IDC_CLOSEWINDOW                 1011
#define IDC_BUTTON1                     1011
#define IDC_BTN_REFESH                  1011
#define IDC_EXPORTTABLES                1012
#define IDC_TABLES                      1012
#define IDC_TREEITEMS                   1013
#define IDC_STATUS                      1014
#define IDC_WINSLIST                    1106
#define IDM_CREATE_MINI_DUMP            1135
#define IDC_RESULT                      1136
#define IDM_EXPAND                      40000
#define IDM_COLLAPSE                    40001
#define IDM_GROUP                       40002
#define IDM_DEATCH_DEBUGGER             40003
#define IDM_ABOUT                       40004
#define IDM_SETTINGS                    40005
#define IDM_TEXIT                       40006
#define ID_THREADMENU_KILLTHREAD        40007
#define IDM_TREBOT                      40008
#define ID_THREADMENU_SURTHREAD         40009
#define ID_THREADMENU_RESUTHREAD        40010
#define IDM_SPYWIN                      40011
#define ID_WINSMENU_SPYWIN              40012
#define IDM_SYSTEM_SLEEP                40017
#define IDM_SYSTEM_SHUTDOWN             40018
#define IDM_SYSTEM_REBOOT               40019
#define ID_WINSMENU_SETTO               40020
#define ID_WINSMENU_TOTOP               40021
#define ID_WINSMENU_MIN                 40022
#define ID_WINSMENU_MAX                 40023
#define ID_WINSMENU_END                 40024
#define ID_WINSMENU_CLOSE               40025
#define ID_MAINWINMENU_SETTO            40026
#define ID_MAINWINMENU_BRINGFORNT       40027
#define ID_MAINWINMENU_MAX              40028
#define IDM_KILLPROCTREE                40029
#define IDM_KILLKERNEL                  40030
#define IDM_KILL                        40031
#define IDM_OPENPATH                    40032
#define IDM_FILEPROP                    40033
#define ID_MAINWINMENU_SELECTITEM       40034
#define ID_MODULSMENU_FILEPROP          40035
#define ID_MODULSMENU_OPENPATH          40036
#define IDM_VTHREAD                     40039
#define IDM_VMODULS                     40040
#define IDM_VWINS                       40041
#define IDM_VHANDLES                    40042
#define IDM_REBOOT_AS_ADMIN             40043
#define IDM_LOAD_DRIVER                 40044
#define IDM_UNLOAD_DRIVER               40045
#define ID_FMMAIN_REFESH                40055
#define ID_FMMAIN_OPEN                  40056
#define ID_FMMAIN_OPENWAY               40057
#define ID_FMMAIN_CUT                   40058
#define ID_FMMAIN_PTASE                 40059
#define ID_FMMAIN_COPY                  40060
#define ID_FMMAIN_DEL                   40061
#define ID_FMMAIN_REMOVE                40062
#define ID_FMMAIN_RENAME                40063
#define ID_FMMAIN_COPYTO                40064
#define ID_FMMAIN_MOVETO                40065
#define ID_FMMAIN_NEW                   40066
#define ID_FMMAIN_NEWFOLDER             40067
#define ID_WINSMENU_HIDEWINDOW          40068
#define ID_FMMAIN_NOSEL                 40069
#define ID_FMMAIN_RESEL                 40070
#define ID_FMMAIN_PROP                  40071
#define ID_FMM_READ                     40072
#define ID_FMM_READONLY                 40073
#define ID_FMM_HIDDEN                   40074
#define ID_FMM_SYSTEM                   40075
#define ID_FMMAIN_SHIWHIDEDFILES        40077
#define ID_FMMAIN_SELALL                40078
#define ID_FMFOLDER_PROP                40088
#define ID_FMFOLDER_COPYPATH            40089
#define ID_FMFOLDER_RENAME              40090
#define ID_FMFOLDER_REMOVE              40091
#define ID_FMFOLDER_DEL                 40092
#define ID_FMFOLDER_PTASE               40093
#define ID_FMFOLDER_CUT                 40094
#define ID_FMFOLDER_COPY                40095
#define ID_FMFOLDER_OPENINEXP           40096
#define ID_FMFOLDER_OPEN                40097
#define ID_FMMAIN_40098                 40098
#define ID_FMMAIN_COPYPATH              40099
#define ID_SCSMALL_STOPSC               40103
#define ID_SCSMALL_REBOOTSC             40104
#define ID_SCSMALL_GOTOSC               40105
#define IDM_RUN                         40108
#define IDM_REFESH_FAST                 40113
#define IDM_REFESH_SLOW                 40114
#define IDM_REFESH_PAUSED               40115
#define IDM_TOPMOST                     40117
#define IDM_CLOSETOHIDE                 40120
#define IDM_MINHIDE                     40121
#define IDM_SOFT_OP                     40123
#define ID_SCMAIN_COPYPATH              40133
#define ID_SCMAIN_DEL                   40134
#define ID_SCMAIN_DISABLE               40135
#define ID_SCMAIN_AUTOSTART             40136
#define ID_SCMAIN_NOAUTOSTART           40137
#define ID_SCMAIN_REBOOT                40138
#define ID_SCMAIN_START                 40139
#define ID_SCMAIN_STOP                  40140
#define ID_SCMAIN_REFESH                40141
#define ID_SCMAIN_RESU                  40144
#define ID_SCMAIN_SUSP                  40145
#define ID_MENUDRIVER                   40146
#define ID_MENUDRIVER_REFESH            40165
#define ID_MENUDRIVER_DELETE            40166
#define ID_MENUDRIVER_DELETEREGANDFILE  40167
#define ID_MENUDRIVER_CHECKVERY         40168
#define ID_MENUDRIVER_CHECK_ALLVERY     40169
#define ID_MENUDRIVER_SHOWALLDRIVER     40170
#define ID_MENUDRIVER_COPYPATH          40171
#define ID_MENUDRIVER_COPYREG           40172
#define ID_MENUDRIVER_OPENPATH          40173
#define ID_MENUDRIVER_SHOWPROP          40174
#define ID_MENUDRIVER_START_BOOT        40175
#define ID_MENUDRIVER_START_SYSTEM      40176
#define ID_MENUDRIVER_START_AUTO        40177
#define ID_MENUDRIVER_START_DEMAND      40178
#define ID_MENUDRIVER_START_DISABLE     40179
#define ID_MENUDRIVER_UNLOAD            40180
#define ID_SIMPPROC_NEWTASK             40183
#define ID_SIMPPROC_ENDTASK             40184
#define ID_SIMPPROC_SETTO               40185
#define IDM_SETTO                       40186
#define ID_USER_CONNECT                 40189
#define ID_USER_DISCONNECT              40190
#define ID_USER_LOGOOFF                 40191
#define ID_TASKMENU_SETAFFINITY         40199
#define ID_SETPRIORTY_REALTIME          40202
#define ID_SETPRIORTY_HIGH              40203
#define ID_SETPRIORTY_ABOVENORMAL       40204
#define ID_SETPRIORTY_NORMAL            40205
#define ID_SETPRIORTY_BELOWNORMAL       40206
#define ID_SETPRIORTY_LOW               40207
#define ID_THREADMENU_KILLKERNEL        41008
#define ID_WINSMENU_SHOWWND             41009
#define IDM_REFESH                      41012
#define IDM_SYSTEM_LOGOFF               41020
#define ID_WINSMENU_DISABLE             41026
#define IDM_SUPROC                      41027
#define IDM_RESPROC                     41028
#define ID_MAINWINMENU_MIN              41029
#define ID_MAINWINMENU_END              41030
#define ID_MENUWINMAIN_SPY              41031
#define ID_MAINWINMENU_SPYWIN           41032
#define ID_WINSMENU_ENABLE              41127
#define ID_WINSMENU_SHOWREGION          41128
#define IDC_REFESH                      41130
#define ID_MODULSMENU_FREELIB           41139
#define IDC_MENUSTART_DELREG            41140
#define IDC_MENUSTART_DELREGANDFILE     41141
#define IDC_MENUSTART_COPYPATH          41142
#define IDC_MENUSTART_COPYREGPATH       41143
#define IDC_MENUSTART_OPENPATH          41144
#define IDC_MENUSTART_OPENREGPATH       41145
#define IDC_SOFTACT_SHOWSPY             41146
#define IDC_SOFTACT_SHOWFILETOOL        41147
#define ID_FMMAIN_FORCE_REMOVE          41148
#define ID_FMFOLDER_FORCE_REMOVE        41149
#define IDC_SOFTACT_TEST1               41150
#define IDM_SYSTEM_FORCE_SHUTDOWN       41151
#define IDM_SYSTEM_FORCE_REBOOT         41152
#define IDC_SOFTACT_TEST2               41153
#define IDC_SOFTACT_SHOWDRIVER_LOADERTOOL 41154
#define IDM_VKSTRUCTS                   41155
#define IDM_VTIMER                      41156
#define IDM_VHOTKEY                     41157
#define IDM_DEBUG                       41158
#define ID_THREADMENU_FILEPROP          41159
#define ID_THREADMENU_OPENPATH          41160
#define IDM_SGINED                      41161
#define IDC_SOFTACT_SHOW_KDA            41162
#define IDC_SOFTACT_TEST3               41163
#define IDC_PCMGR_CMD                   41164
#define ID_FMMAIN_CNECK_USING           41165
#define IDM_VPRIVILEGE                  41166
#define IDM_DBGVIEW                     41167
#define IDC_PCMGR_KERNEL_TOOL           41168
#define IDC_PCMGR_HOOK_TOOL             41169
#define IDC_PCMGR_NETMON                41170
#define IDC_PCMGR_REGEDIT               41171
#define IDC_PCMGR_FILEMGR               41172
#define IDM_RELOADPDB                   41173
#define IDM_SYSTEM_HIBERNATE            41174
#define IDM_ALWAYSTOP                       41175
#define IDM_CANCELTOP                       41176
#define IDM_SHOWBORDER                      41177
#define IDM_START_MHOOK                     41178
#define IDM_END_MHOOK                      41179
#define IDM_SE_AOT                      41180
#define IDC_CLOSE_PCMGR_CMD 41181
#define IDM_HELP 41182


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40208
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
